### ISSUE TITLE
A question about the code......

### ISSUE THREAD

**Issue by gh18l** [junyanz/light-field-video#1]
I have compiled the matcaffe, but when I tried to run the code, I met the problem:

`>> main
Invalid MEX-file '/home/aaa/Downloads/light-field-video/traintestcode/code/model/caffe/matlab/+caffe/private/caffe_.mexa64':
/home/aaa/Downloads/light-field-video/traintestcode/code/model/caffe/matlab/+caffe/private/caffe_.mexa64: undefined symbol:
_ZN5boost6thread21start_thread_noexceptEv

Error in caffe.reset_all (line 5)
caffe_('reset');

Error in networkInit (line 4)
caffe.reset_all();

Error in main (line 5)
[disp_net, flow_net, warpAndColor_net] = networkInit();  % the four networks used in our system`

I have tried re-installing the boost through "sudo apt-get autoremove libboost1.58-dev   sudo apt-get install libboost-all-dev", but it does not work. What can I do to run the code? Thank you!

**Comment by tcwang0509** [comment]
It looks like it's a caffe problem. Are you able to pass the caffe run test?

**Comment by gh18l** [comment]
I have passed the official caffe, but don't pass your caffe version. I changed my ubuntu16 to ubuntu14, and it works well, thank you!
