### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by abrahamyan-lusine** [junyanz/light-field-video#3]
Hi, 
Could you please explain how you get different views of 1 frame of light field image in PNG representation?

**Comment by junyanz** [comment]
We stored different views in an 8x8 grid. [Here](https://github.com/junyanz/light-field-video/blob/master/src/LFVideo.cpp#L220) is the code that reads multiple views from the png file.

**Comment by abrahamyan-lusine** [comment]
thanks)
